version: '3'
services:
   sensibled:
     build: .
     image: jiedo/sensibled:v1.10.1
     entrypoint: ./sensibled -end 710000 -batch 960000
     volumes:
       - /data/bitcoind/data/blocks:/data/blocks:ro
       - ./conf:/data/conf:ro
       - ./cmd:/data/cmd
     labels:
       - "name=sensibled-batch"
     logging:
       driver: "json-file"
       options:
         labels: "name"
         max-size: "1g"
         max-file: "3"
