version: '3'
services:
   sensibled:
     build: .
     image: sensibled:v1.5.1
     entrypoint: ./sensibled -end 680000 -batch 960000
     volumes:
       - /data/bitcoin-sv-blocks/blocks:/data/bitcoin-sv-blocks/blocks:ro
       - ./conf:/data/conf:ro
       - ./cmd:/data/cmd
     labels:
       - "name=sensibled-batch"
     logging:
       driver: "json-file"
       options:
         labels: "name"
         max-size: "1g"
         max-file: "3"
