version: '3'
services:
   satoblock:
     build: .
     image: satoblock:v2.1
     entrypoint: ./satoblock
     volumes:
       - /data/bitcoin-sv-blocks/blocks:/data/bitcoin-sv-blocks/blocks:ro
       - ./conf:/data/conf:ro
       - ./cmd:/data/cmd
     logging:
       driver: "local"
       options:
         max-size: "5g"
