version: '3'
services:
   sensibled:
     build: .
     image: jiedo/unisatd:v1.0.2
     entrypoint: ./sensibled
     volumes:
       - /data/bitcoind/data/blocks:/data/blocks:ro
       - ./conf:/data/conf:ro
       - ./cmd:/data/cmd
     ports:
       - "6666:8000"
     labels:
       - "name=sensibled"
     logging:
       driver: "json-file"
       options:
         labels: "name"
         max-size: "1g"
         max-file: "3"
