version: '3'
services:
   sensibled:
     build: .
     image: jiedo/sensibled:v1.5.5
     entrypoint: ./sensibled -full -end 100000
     volumes:
       - /data/bitcoin-sv-blocks/blocks:/data/bitcoin-sv-blocks/blocks:ro
       - ./conf:/data/conf:ro
       - ./cmd:/data/cmd
     labels:
       - "name=sensibled-init"
     logging:
       driver: "json-file"
       options:
         labels: "name"
         max-size: "1g"
         max-file: "3"
